### PR TITLE
Animated Buttons Done

### PR DESCRIPTION
**Pull request by kaushal1717**
Issue #209 solved 
Made both animated buttons

### CODE REVIEW

**Comment by Debajyoti14** [comment]
@kaushal1717 Can you fix these merge conflicts?

**Comment by kaushal1717** [comment]
Okk

**Comment by Debajyoti14** [comment]
@kaushal1717 You have used 3rd party libraries to implement animated buttons. We don't accept such PRs. Can you make another PR by making the changes?

**Comment by kaushal1717** [comment]
It means I can't use MaterialButtons?

**Comment by kaushal1717** [comment]
okk working on it

**Pull request closed without merging**
