### PR TITLE
Added Search Feature for Widgets

### LINKED ISSUE #186: Adding the search feature in the project
**Is your feature request related to a problem? Please describe.**
Currently there is no such method to search for the widgets you are trying to search for.

**Describe the solution you'd like**
Converting the widgets to a list and then searching for the search controller keyword and if it matches add to results.

**Additional context**
I have tried to implement it and i have a basic design on how to implement it.
Screenshot 2023-05-24 130932

### PR DESCRIPTION
**Pull request by Uttkarsh-raj**
### Pull Request Template

**Description:**

Added the search feature.

**Changes Made:**

added a new search bar and search button with a way to match the searched item to the widgets and return the results.

**Related Issue:**

If applicable, reference the related issue number(s) here.

**Screenshots/GIFs:**

Screenshot 2023-05-25 113550
Screenshot 2023-05-25 113610
Screenshot 2023-05-25 113529

**Related Issue:**
Related to the issue of adding a search feature fixed #186 

**Testing Done:**

Write the name or the type of the widget you want to search and then press the search button, the results will be displayed.

**Additional Notes:**

Write the name or the type of the widget you want to search and then press the search button, the results will be displayed.

**Checklist:**

- [ ] The code follows the project's coding style guidelines.
- [ ] Unit tests have been added or updated to cover the changes.
- [ ] Documentation, if applicable, has been updated to reflect the changes.
- [ ] All new and existing tests pass successfully.

Please review and merge this PR at your earliest convenience.

Thank you!

### CODE REVIEW

**Comment by Roshaen** [comment]
@Uttkarsh-raj I'll review and merge it today

**Comment by Uttkarsh-raj** [comment]
Hey @Roshaen  can you review the level too since there is another issue with the search feature and it is level 3 and i think this issue also is similar and should be on level 3 (just a suggestion).

**Comment by Roshaen** [comment]
Hey @Uttkarsh-raj can you change the width of the search bar and search button and keep it inside the default padding of the elements

**Comment by Roshaen** [comment]
> Hey @Roshaen can you review the level too since there is another issue with the search feature and it is level 3 and i think this issue also is similar and should be on level 3 (just a suggestion).

Ok I'll look into it

**Comment by Uttkarsh-raj** [comment]
> Hey @Uttkarsh-raj can you change the width of the search bar and search button and keep it inside the default padding of the elements

So i should increase the width of the search bar?

**Comment by Uttkarsh-raj** [comment]
> Hey @Uttkarsh-raj can you change the width of the search bar and search button and keep it inside the default padding of the elements

I have made the changes and also added the new widget added to the search bar... should i create a new pr?

**Pull request closed without merging**
