### PR TITLE
The Issue related to the Bottom_Navigation_Bar has been resolved.

### PR DESCRIPTION
**Pull request by Rhishikesh12**
### Pull Request Template

**Description:**
The pull request addresses the bug found in the Spectrum UI app, specifically issue #201. This bug has been resolved, and the Bottom_Navbar page has been implemented as part of the changes.

**Changes Made:**

When I discovered the bug, an incorrect function was being passed to the Bottom_Navbar page, resulting in the wrong page (alertpage) opening when the user clicked on the Bottom_NavBar card. To address this issue, I resolved it by implementing the Bottom_Navbar page and passing the correct function

**Related Issue:**

Issue #201 

**Screenshots/GIFs:**
image
Solved
image
image

**Additional Notes:**
Additional bottom_navigation designs can be included to provide more options and variations for users to choose from, enhancing the visual appeal and user experience of the application.

**Checklist:**

- [✅ ] The code follows the project's coding style guidelines.

Please review and merge this PR at your earliest convenience.

Thank you!

### CODE REVIEW

**Comment by Rhishikesh12** [comment]
The issue has been resolved. Please review and merge the pull request at your convenience and provide feedback.

**Comment by Rhishikesh12** [comment]
I have a question: What do Level 1, Level 2, and Level 3 tags represent?

I implemented the Bottom_Navigation_Bar page that was initially missing, so I expected my issue (#201) to be assigned a Level 2 tag, considering the added functionality.

**Comment by Debajyoti14** [comment]
@Rhishikesh12 Can you resolve the conflict and commit again?

**Comment by Rhishikesh12** [comment]
@Debajyoti14 I have already resolved the issue. Is there a problem with my Pull Request? Should I make any changes to my code? Or should I create a new Pull Request with the same code?

**Comment by Debajyoti14** [comment]
@Rhishikesh12 Commit again after taking pull

**Comment by Rhishikesh12** [comment]
> @Rhishikesh12 Commit again after taking pull

Actually I didn't understand what you're saying 😅 I am bit confused, sorry but can you please clear my doubt.

**Comment by Debajyoti14** [comment]
@Rhishikesh12 When you will take a pull from main, then you will have merge conflicts. Fix that and commit again

**Comment by Debajyoti14** [comment]
@Rhishikesh12 Great Work 👍

**Comment by Debajyoti14** [comment]
@Rhishikesh12 We don't use any third party packages or libraries in our code

**Comment by Rhishikesh12** [comment]
> @Rhishikesh12 We don't use any third party packages or libraries in our code

Okay sir, let me remove all the third party packages. Does this task need to be reassigned to me?

**Pull request merged**
